name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker image build -t venomuz/kegel-backend .

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} $(echo $REGISTRY)

      - name: Push to DockerHub
        run: docker push venomuz/kegel-backend


  deploy_to_server:
    environment: production
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        env:
          SERVER_NAME: "kegel-backend"
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            # Login into Digital Ocean Registry
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} $(echo $REGISTRY)

            # Run a new container from a new image
            cd /root/kegel-backend
            git pull --force
            docker compose down
            docker compose pull
            docker-compose up -d --force-recreate nginx
