# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker image build -t venomuz/kegel-backend .

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} $(echo $REGISTRY)

      - name: Docker push
        run: docker push venomuz/kegel-backend


  deploy:
    environment: production
    runs-on: ubuntu-latest
    needs: build

    steps:
#      - uses: actions/checkout@master
#      - name: copy file via ssh password
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          key: ${{ secrets.SSHKEY }}
#          target: "api"
#          strip_components: 1
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        env:
          SERVER_NAME: "kegel-backend"
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            # Login into Digital Ocean Registry
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} $(echo $REGISTRY)

            # Run a new container from a new image
            cd /root/go/src/github.com/venomuz/kegel-backend
            docker compose down
            docker compose pull
            docker compose up -d